#!/bin/sh

check_commands() {
	local missing=0
	for tool in "$@"; do
		if ! command -v "$tool" > /dev/null; then
			echo "$tool missing."
			missing=1
		fi
	done
	return $missing
}

# Check for required tools.
required_commands="git nvim yarn"
if ! check_commands $required_commands; then
	exit 1
fi

if ! command -v "clangd" > /dev/null; then
	echo "Consider installing clang for C++ code completion."
fi

nvim +PaqSync +qall
