#!/bin/sh

check_commands() {
	local missing=0
	for tool in "$@"; do
		if ! command -v "$tool" > /dev/null; then
			echo "$tool missing."
			missing=1
		fi
	done
	return $missing
}

# Check for required tools.
required_commands="git nvim yarn"
if ! check_commands $required_commands; then
	exit 1
fi

if ! command -v "ccls" > /dev/null; then
	echo "Consider installing ccls for C++ code completion."
fi

curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
nvim +PlugInstall +qall
